CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE TABLE IF NOT EXISTS users(
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 name VARCHAR(120) NOT NULL,email VARCHAR(255) UNIQUE NOT NULL,
 password_hash TEXT,role VARCHAR(40) NOT NULL DEFAULT 'user',
 created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS audit_logs(
 id BIGSERIAL PRIMARY KEY,user_id UUID REFERENCES users(id),
 action VARCHAR(160) NOT NULL,metadata JSONB DEFAULT '{}',
 created_at TIMESTAMPTZ DEFAULT NOW()
);
